### ISSUE TITLE
Can't Get Open Refine to Install

### ISSUE THREAD

**Issue by ghost** [CSCI-4830-002-2014/challenge-week-4#4]
Hi all,

Whenever I download the .dmg from the download page for my Mac and install it, my computer says "'Google Refine' is damaged and cannot be opened. You should move it to the trash." I've tried installing it five times now. Mac users, how did you get it working on your Mac?

**Comment by wannabeCitizen** [comment]
It's because of your security settings on your Mac: https://code.google.com/p/google-refine/issues/detail?id=591

**Comment by ghost** [comment]
That fixed my issue. Thanks!
